---
Title: "WOW Power BI 2025 week 13 demonstration"
---

# Sanky Chart and Table
I used the PowerBpy python module to recreate an <a href="https://workout-wednesday.com/pbi-2025-w13/">sanky chart and table</a> dashboard from the <a href="https://workout-wednesday.com/">Workout Wednesday Group</a> challenge. Here's a screenshot of the original dashboard (left) and the dashboard I recreated using Power Bpy (right). (It appears that the data has changed since the original author created his dashboard, so my version and his look a bit different because the data is a bit different, but the overall format is pretty similiar). The rest of the blog will describe key parts of the code I used to make the dashboard. The full code is available <a href="">here</a>.

# Setup   
## Assumptions
This example assumes that you already have python installed and setup and that you know how to install python modules such as pandas.If you don't, please refer to basic setup instructions on this page or find one of the many great resources online that explains how to install python packages.  

## Obtain and prepare data
One of the central assumptions built into the PowerBpy package is that you'd prefer to write python code over using Power BI. Therefore this example will avoid writing any M or DAX and will instead use python to extract, load and transform the data. Once the data is ready will use PowerBpy to create the dashboard. 

 
## Download Data
The data for this example is stored as an online zip file. The following code downloads the zip file and extracts it into a local directory. 
```python
import requests
import py7zr
import os
import tempfile

'''
This script downloads the data from Github and 
then extracts the individual datasets from the compressed archive file. 



'''

# step 1: obtain data from github --------------------------------------------------------------

# Define paths
dataset_url = "https://github.com/sql-bi/Contoso-Data-Generator-V2-Data/releases/download/ready-to-use-data/csv-10k.7z" 
data_destination_dir = "data"


# make sure the folder exists
os.makedirs(data_destination_dir, exist_ok=True)

# download the zip file from the internet
response = requests.get(dataset_url, stream=True)
response.raise_for_status()

# write to file
with tempfile.NamedTemporaryFile(suffix=".7z", delete=False) as tmp_file:
    with open(tmp_file.name, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)



# extract the data 
with py7zr.SevenZipFile(tmp_file.name, mode="r") as z:
    z.extractall(path=data_destination_dir)


```    

## Process data


