---
title: "basic_setup"
format: html
---

# Setup
## Python
1. Make sure [python](https://www.python.org/downloads/) is installed on your computer.

## Create virtual environment
For this example, we're going to use a virtual environment to keep the package versions separate from what you have installed on your system
1. Open a command prompt and navigate to the folder you want to create dashboards in by running the following:
   ```shell
   cd path/to/your/folder
   ```
2. Create and activate a virtual environment by running the same:
   ```shell
   # create a virtual environment
   python -m venv venv

   # for windows
   venv\Scripts\activate.bat

   # for linux or Mac (remove hashtag first)
   # source venv/bin/activate
   ```
   
2. Install the Power Bpy module:
   ```shell
   # install the Power Bpy module
   pip install powerbpy
   ```
   
3. Write a script to create a dashboard. (This one's up to you!)

4. When you're ready to create the dashboard, run the script by running the following in the command prompt window.

  ```shell
  python name_of_your_script.py
  ```     
  
  
## Install dependencies
1. Install python        
You'll need to install python. Here are some <a href="https://www.geeksforgeeks.org/download-and-install-python-3-latest-version/">instructions</a>    
2. Install Power Bpy    
The `{powerbpy}` package isn't on pypi yet, so you'll need to install it from github. <a href="https://www.lifewire.com/how-to-open-command-prompt-2618089">Open a terminal</a> and enter the following:     
    
```dosbat     
py -m pip install git+https://github.com/Russell-Shean/powerbpy.git#egg=powerbpy     
```     
   
After the package is on pypi, you'll be able to install it using this: 
```batchfile
py -m pip install powerbpy
```
   
## Executing python scripts   
That's all you need to install! To create the dashboards, you'll need to either run the commands in a terminal, or use a text editor to save the commands in a a script. I recomend starting with a text editor, because as your dashboard grows more complex, it'll be helpful to have everything saved in a script. Many text editors have an option to execute a script directly from the editor. You can also execute the scripts from the terminal using the following command:     
```dosbat
py build_dashboard.py
```  
This assumes that you named your script `build_dashboard.py` and the command prompt's current directory is the folder storing `build_dashboard.py`. You can change the current directory of the terminal using the `cd` command. For example you can use the following to move into `C:/Users/`:     
```dosbat
cd C:/Users/
```
You can also use full or relative paths from the current directory to the python script without changing the current working directory. For example if you start in your `%userprofile%` (`C:/Users/[your username]`) and the python script is stored at `C:/Users/[your username]/python_projects/build_dashboard.py`, you can execute the script with the following:     
```dosbat      
py python_projects/build_dashboard.py    
```    