name: Build and publish quartodoc site

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev-*"]
  pull_request:
  release:
    types: [published]

jobs:
   build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install dependencies
        run: |
          # install quartodoc and other things we may need?
          python -m pip install quartodoc
          python -m pip install shiny shinylive
          python -m pip install --no-deps dascore==0.0.8
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build docs
        run: |

          # Set git credentials for later on
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

          
          # copy the readme file into the docs folder
          # and overwrite index.md 
          cp -rf ./README.md ./docs/index.md
          ls ./docs

          
          # move into the src folder 
          # so we don't have to build the package for this to work
          cd src

          # build the docs
          quartodoc build --config ../docs/_quarto.yml

          # move back to original directory
          cd ..

          #git status
          #git add .
          #git commit -m "commit site files back"
          #git push

          # publish manually without everyone else's broken actions
          quarto publish gh-pages ./docs --no-browser --no-prompt
 
      # commit all this junk back to the repo
      #- uses: stefanzweifel/git-auto-commit-action@v5


      #- name: Render and Publish
       # uses: quarto-dev/quarto-actions/publish@v2
       # with:
        #  target: gh-pages
        #  path: docs
        #env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   #deploy-gh-pages:
    #runs-on: ubuntu-latest
    #permissions:
    #  contents: write
    #steps:
    #  - uses: actions/checkout@v4
    #  - name: Deploy to GitHub pages 🚀
    #    if: github.event_name != 'pull_request'
    #    uses: JamesIves/github-pages-deploy-action@v4.5.0
    #    with:
    #      clean: false
    #      branch: gh-pages
    #      folder: docs

