name: Build and publish quartodoc site

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev-*"]
  pull_request:
  release:
    types: [published]

jobs:
   build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install dependencies
        run: |
          # install quartodoc and other things we may need?
          python -m pip install quartodoc
          python -m pip install shiny shinylive
          python -m pip install --no-deps dascore==0.0.8
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build docs
        run: |
          # move into the src folder 
          # so we don't have to build the package for this to work
          cd src

          # build the docs
          quartodoc build --config ../docs/_quarto.yml

          # hopefully that's enough?

