name: Build and publish quartodoc site

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev-*"]
  pull_request:
  release:
    types: [published]

jobs:
   build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install dependencies
        run: |
          # install quartodoc and other things we may need?
          python -m pip install quartodoc
          python -m pip install shiny shinylive
          python -m pip install --no-deps dascore==0.0.8
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build docs
        run: |
          # copy the readme file into the docs folder
          # and overwrite index.md 
          cp -fr README.md /docs/index.md

          
          # move into the src folder 
          # so we don't have to build the package for this to work
          cd src

          # build the docs
          quartodoc build --config ../docs/_quarto.yml

          # move back to original directory
          cd ..

      #- name: Render and Publish
       # uses: quarto-dev/quarto-actions/publish@v2
       # with:
        #  target: gh-pages
        #  path: docs
        #env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs

