table colony
	lineageTag: 8dd5fb4d-b03f-4d4c-aa55-4f0d2bf2fe22

	column year
		dataType: double
		lineageTag: ba09f076-97ff-4b14-996a-fb3da500aaff
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column months
		dataType: string
		lineageTag: dca60b1b-e07d-40f8-a78b-1add6fe2bdb5
		summarizeBy: none
		sourceColumn: months

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: ad8082bf-5b6b-4ae4-b01c-679869261866
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column colony_n
		dataType: double
		lineageTag: efd7199a-b353-4de3-92ea-ef9b6ae20184
		summarizeBy: sum
		sourceColumn: colony_n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_max
		dataType: double
		lineageTag: 0d1bbf38-f3b5-4b1b-83a6-f1da848b35c8
		summarizeBy: sum
		sourceColumn: colony_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_lost
		dataType: double
		lineageTag: d753f152-5c24-45c0-b788-2b3e58051afe
		summarizeBy: sum
		sourceColumn: colony_lost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_lost_pct
		dataType: double
		lineageTag: 572846ec-f696-4765-91da-c1e5e2ae0194
		summarizeBy: sum
		sourceColumn: colony_lost_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_added
		dataType: double
		lineageTag: 4ea5e50d-0430-4e2a-acc9-2f1c574b5a90
		summarizeBy: sum
		sourceColumn: colony_added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_reno
		dataType: double
		lineageTag: c80e8839-dbba-43a5-bbaf-4d9ca81a003f
		summarizeBy: sum
		sourceColumn: colony_reno

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_reno_pct
		dataType: double
		lineageTag: ca0b4033-626c-4b60-a1e0-720546832306
		summarizeBy: sum
		sourceColumn: colony_reno_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition colony = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\colony.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"year", "months", "state", "colony_n", "colony_max", "colony_lost", "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"year", type number}, {"months", type text}, {"state", type text}, {"colony_n", type number}, {"colony_max", type number}, {"colony_lost", type number}, {"colony_lost_pct", type number}, {"colony_added", type number}, {"colony_reno", type number}, {"colony_reno_pct", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

