table colony
	lineageTag: 98a97dba-948f-4178-948b-2a00d01d7a4a

	column 'year'
		dataType: double
		lineageTag: 7d3fd0b3-8ef1-410a-93ab-dce9e0878ce8
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'months'
		dataType: string
		lineageTag: 09d9abd9-e683-4e31-9386-44e9da7c5eae
		summarizeBy: none
		sourceColumn: months

		annotation SummarizationSetBy = Automatic

	column 'state'
		dataType: string
		lineageTag: c6b9e364-cbe4-4a97-94b2-30c4f7499ab2
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column 'colony_n'
		dataType: double
		lineageTag: 36fd1a7f-3fc8-4d7e-a749-23325998927e
		summarizeBy: sum
		sourceColumn: colony_n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_max'
		dataType: double
		lineageTag: 7749f344-d86c-4cc4-b6c3-8611e06807bc
		summarizeBy: sum
		sourceColumn: colony_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost'
		dataType: double
		lineageTag: 60a6c3cd-d653-4426-943e-995df770fbf0
		summarizeBy: sum
		sourceColumn: colony_lost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost_pct'
		dataType: double
		lineageTag: 5d029177-d15d-47e1-837b-390a7e951a06
		summarizeBy: sum
		sourceColumn: colony_lost_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_added'
		dataType: double
		lineageTag: cb0a8e38-59ed-4ed8-9c20-3a053f650065
		summarizeBy: sum
		sourceColumn: colony_added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno'
		dataType: double
		lineageTag: d5763850-e20b-43a7-bf21-51ed83bbf6c3
		summarizeBy: sum
		sourceColumn: colony_reno

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno_pct'
		dataType: double
		lineageTag: 14f9d62d-8b6c-42de-9a64-84207d77a2dc
		summarizeBy: sum
		sourceColumn: colony_reno_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition colony = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("\home\russ\Documents\coding_projects\portfolio_projects\powerbpy\examples\data\colony.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"year", "months", "state", "colony_n", "colony_max", "colony_lost", "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"year", type number}, {"months", type text}, {"state", type text}, {"colony_n", type number}, {"colony_max", type number}, {"colony_lost", type number}, {"colony_lost_pct", type number}, {"colony_added", type number}, {"colony_reno", type number}, {"colony_reno_pct", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

