table colony
	lineageTag: eb75f7f3-b76d-4c0e-a6c1-8f064a4bf3fd

	column 'year'
		dataType: double
		lineageTag: c8851620-3ca0-418d-acdd-3bc2a7e68657
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'months'
		dataType: string
		lineageTag: dfc9dd35-7f23-4554-ba89-3fbe4bd47464
		summarizeBy: none
		sourceColumn: months

		annotation SummarizationSetBy = Automatic

	column 'state'
		dataType: string
		lineageTag: 8899fbdf-ee81-47d0-a00f-c08ebf11d74b
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column 'colony_n'
		dataType: double
		lineageTag: 1f4a592c-f370-4f48-8113-dd53d38ca6ca
		summarizeBy: sum
		sourceColumn: colony_n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_max'
		dataType: double
		lineageTag: f2302a2c-7574-4c96-a7f9-7a5d37e8f952
		summarizeBy: sum
		sourceColumn: colony_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost'
		dataType: double
		lineageTag: 8440ce43-d6d1-431f-9844-b26c27912d0d
		summarizeBy: sum
		sourceColumn: colony_lost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost_pct'
		dataType: double
		lineageTag: 6272854a-e122-44d0-aa82-7b81aae0f7f8
		summarizeBy: sum
		sourceColumn: colony_lost_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_added'
		dataType: double
		lineageTag: 16aa275e-7116-4b24-ac61-b68b95c1e572
		summarizeBy: sum
		sourceColumn: colony_added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno'
		dataType: double
		lineageTag: 40b8aee7-6deb-4b5b-b9af-a74fbd69f73e
		summarizeBy: sum
		sourceColumn: colony_reno

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno_pct'
		dataType: double
		lineageTag: 2f67b72b-ea76-43f4-8f8d-dcf71131a718
		summarizeBy: sum
		sourceColumn: colony_reno_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition colony = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\colony.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"year", "months", "state", "colony_n", "colony_max", "colony_lost", "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"year", type number}, {"months", type text}, {"state", type text}, {"colony_n", type number}, {"colony_max", type number}, {"colony_lost", type number}, {"colony_lost_pct", type number}, {"colony_added", type number}, {"colony_reno", type number}, {"colony_reno_pct", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

