table colony
	lineageTag: 8aeb6b66-7a37-4ce3-84b3-c09a2f8ea71f

	column 'year'
		dataType: double
		lineageTag: 5ff45fc7-6b4d-4527-81ae-3cb6ac7dcb89
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'months'
		dataType: string
		lineageTag: 91a8f798-a049-4897-8b02-a34683fec489
		summarizeBy: none
		sourceColumn: months

		annotation SummarizationSetBy = Automatic

	column 'state'
		dataType: string
		lineageTag: 589f54c1-efe4-4765-a4a1-9946231fa4a5
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column 'colony_n'
		dataType: double
		lineageTag: 1bc83820-ad13-40ea-a925-427d0f3a0ea4
		summarizeBy: sum
		sourceColumn: colony_n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_max'
		dataType: double
		lineageTag: 70a2dd9b-6786-4e58-87f1-2414c76e1672
		summarizeBy: sum
		sourceColumn: colony_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost'
		dataType: double
		lineageTag: db89fbb6-9aa0-4359-8647-1deddeba9cec
		summarizeBy: sum
		sourceColumn: colony_lost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost_pct'
		dataType: double
		lineageTag: a30837ae-a102-4c5c-af01-d6a38305b9dc
		summarizeBy: sum
		sourceColumn: colony_lost_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_added'
		dataType: double
		lineageTag: 4352d2e9-9707-4103-b2a4-24ac23589cd3
		summarizeBy: sum
		sourceColumn: colony_added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno'
		dataType: double
		lineageTag: 940133de-83d5-463b-8df6-a1f75691595f
		summarizeBy: sum
		sourceColumn: colony_reno

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno_pct'
		dataType: double
		lineageTag: 13351710-6574-4ee0-8012-2aa5af8b35c4
		summarizeBy: sum
		sourceColumn: colony_reno_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition colony = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\colony.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"year", "months", "state", "colony_n", "colony_max", "colony_lost", "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"year", type number}, {"months", type text}, {"state", type text}, {"colony_n", type number}, {"colony_max", type number}, {"colony_lost", type number}, {"colony_lost_pct", type number}, {"colony_added", type number}, {"colony_reno", type number}, {"colony_reno_pct", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

