table colony
	lineageTag: 4fceb011-01e4-4055-91f4-65b576809ba2

	column year
		dataType: double
		lineageTag: 4e4c973b-e263-46a3-9c2e-e1ecdf71f7fa
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column months
		dataType: string
		lineageTag: a83b748d-d708-4edc-8708-c195ffae6942
		summarizeBy: none
		sourceColumn: months

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 36984f36-56a4-48d1-abc2-2b0ac0584a8e
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column colony_n
		dataType: double
		lineageTag: d0fd6365-3d78-453d-936c-6562757c2c76
		summarizeBy: sum
		sourceColumn: colony_n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_max
		dataType: double
		lineageTag: 9ad459b4-ea6c-4a81-8b71-bf2b5bc7c3ab
		summarizeBy: sum
		sourceColumn: colony_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_lost
		dataType: double
		lineageTag: 7e72c993-ccb1-4369-9314-114345d47d01
		summarizeBy: sum
		sourceColumn: colony_lost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_lost_pct
		dataType: double
		lineageTag: 828854d4-c3d9-47cd-975a-1a0b6aef059e
		summarizeBy: sum
		sourceColumn: colony_lost_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_added
		dataType: double
		lineageTag: 7757541f-2bb6-45b8-8713-9dd53e6ca9e2
		summarizeBy: sum
		sourceColumn: colony_added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_reno
		dataType: double
		lineageTag: f83e2b76-b2d0-486a-a84d-6924ba60599f
		summarizeBy: sum
		sourceColumn: colony_reno

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_reno_pct
		dataType: double
		lineageTag: c27ee518-9c77-4acd-92f8-72dab3e65b64
		summarizeBy: sum
		sourceColumn: colony_reno_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition colony = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\colony.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"year", "months", "state", "colony_n", "colony_max", "colony_lost", "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"year", type number}, {"months", type text}, {"state", type text}, {"colony_n", type number}, {"colony_max", type number}, {"colony_lost", type number}, {"colony_lost_pct", type number}, {"colony_added", type number}, {"colony_reno", type number}, {"colony_reno_pct", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

