table colony
	lineageTag: a61f6746-20f4-458c-a246-c3ef75957573

	column 'year'
		dataType: double
		lineageTag: e3a66f56-cc55-4ed5-b284-47c6df113b15
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'months'
		dataType: string
		lineageTag: a8e8a69e-c64c-4190-a95e-cbbe0ecb9354
		summarizeBy: none
		sourceColumn: months

		annotation SummarizationSetBy = Automatic

	column 'state'
		dataType: string
		lineageTag: 171dae84-70eb-4d89-b64a-bda4cb38718c
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column 'colony_n'
		dataType: double
		lineageTag: abae0337-c97e-42de-87bd-3fe9b0352b91
		summarizeBy: sum
		sourceColumn: colony_n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_max'
		dataType: double
		lineageTag: 38e09516-e240-4350-adc0-89310a39c1fe
		summarizeBy: sum
		sourceColumn: colony_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost'
		dataType: double
		lineageTag: 8fc17a75-1972-408f-8bb2-2b83bf898f67
		summarizeBy: sum
		sourceColumn: colony_lost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_lost_pct'
		dataType: double
		lineageTag: 8973a520-c739-4aca-b982-50d81337bd27
		summarizeBy: sum
		sourceColumn: colony_lost_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_added'
		dataType: double
		lineageTag: 06f6557b-d82b-4e41-95f5-ca3cf6c52aaf
		summarizeBy: sum
		sourceColumn: colony_added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno'
		dataType: double
		lineageTag: 4340d629-df38-4236-9b39-2fa9c3cdc1b2
		summarizeBy: sum
		sourceColumn: colony_reno

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'colony_reno_pct'
		dataType: double
		lineageTag: 0e6643fe-b227-4361-9953-7ed61b6668d3
		summarizeBy: sum
		sourceColumn: colony_reno_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition colony = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\colony.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"year", "months", "state", "colony_n", "colony_max", "colony_lost", "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"year", type number}, {"months", type text}, {"state", type text}, {"colony_n", type number}, {"colony_max", type number}, {"colony_lost", type number}, {"colony_lost_pct", type number}, {"colony_added", type number}, {"colony_reno", type number}, {"colony_reno_pct", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

