table sales_final_dataset
	lineageTag: 9efc33e8-86b7-4272-b783-5df6670be91d

	column 'Name'
		dataType: string
		lineageTag: ffd76300-050a-438d-965a-c37c733fb684
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Sales First 180 Days'
		dataType: double
		lineageTag: d5686d96-9bdc-4223-834c-b6b88517b9af
		summarizeBy: sum
		sourceColumn: Sales First 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Last 180 Days'
		dataType: double
		lineageTag: 217199e3-c153-459c-bb30-d16743dc1698
		summarizeBy: sum
		sourceColumn: Sales Last 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Starting Size'
		dataType: string
		lineageTag: 9da25f6f-8674-44fe-8181-9cf052d8b817
		summarizeBy: none
		sourceColumn: Starting Size

		annotation SummarizationSetBy = Automatic

	column 'Ending Size'
		dataType: string
		lineageTag: d543835d-2d71-41e6-8581-ee69658f7f4c
		summarizeBy: none
		sourceColumn: Ending Size

		annotation SummarizationSetBy = Automatic

	partition sales_final_dataset = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\sales_final_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"Name", "Sales First 180 Days", "Sales Last 180 Days", "Starting Size", "Ending Size"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"Name", type text}, {"Sales First 180 Days", type number}, {"Sales Last 180 Days", type number}, {"Starting Size", type text}, {"Ending Size", type text}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

