table sales_final_dataset
	lineageTag: 151182f5-b14b-48be-9292-80ccfafa3a1a

	column Name
		dataType: string
		lineageTag: 735f0783-8c32-4cea-bf8d-4dc8cd2dd14e
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Sales First 180 Days'
		dataType: double
		lineageTag: dfa4de83-d9be-4f39-9380-8d3edce781b8
		summarizeBy: sum
		sourceColumn: Sales First 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Last 180 Days'
		dataType: double
		lineageTag: f2710722-c7c2-4f97-9512-c000424c4636
		summarizeBy: sum
		sourceColumn: Sales Last 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Starting Size'
		dataType: string
		lineageTag: b13db3cc-106a-447c-961e-d1dbf4c42d4d
		summarizeBy: none
		sourceColumn: Starting Size

		annotation SummarizationSetBy = Automatic

	column 'Ending Size'
		dataType: string
		lineageTag: 103b81e6-9c06-43ff-90c6-6e82acf803c7
		summarizeBy: none
		sourceColumn: Ending Size

		annotation SummarizationSetBy = Automatic

	partition sales_final_dataset = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\sales_final_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"Name", "Sales First 180 Days", "Sales Last 180 Days", "Starting Size", "Ending Size"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"Name", type text}, {"Sales First 180 Days", type number}, {"Sales Last 180 Days", type number}, {"Starting Size", type text}, {"Ending Size", type text}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

