table sales_final_dataset
	lineageTag: 30ad4029-d600-4801-b35b-009f23a694fd

	column 'Name'
		dataType: string
		lineageTag: a5489263-8847-4da7-802f-52a31bde499f
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Sales First 180 Days'
		dataType: double
		lineageTag: ddd19af9-a384-4cdb-bf66-49bcd201b21c
		summarizeBy: sum
		sourceColumn: Sales First 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Last 180 Days'
		dataType: double
		lineageTag: b73d6e6e-026d-46a4-96c3-4d5cc714710f
		summarizeBy: sum
		sourceColumn: Sales Last 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Starting Size'
		dataType: string
		lineageTag: c41ea4e2-0e13-437c-a614-f0ce755c4829
		summarizeBy: none
		sourceColumn: Starting Size

		annotation SummarizationSetBy = Automatic

	column 'Ending Size'
		dataType: string
		lineageTag: a183dff4-1877-4787-a720-3727ed23b2c6
		summarizeBy: none
		sourceColumn: Ending Size

		annotation SummarizationSetBy = Automatic

	partition sales_final_dataset = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\coding_projects\powerbpy\examples\data\sales_final_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"Name", "Sales First 180 Days", "Sales Last 180 Days", "Starting Size", "Ending Size"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"Name", type text}, {"Sales First 180 Days", type number}, {"Sales Last 180 Days", type number}, {"Starting Size", type text}, {"Ending Size", type text}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

