table sales_final_dataset
	lineageTag: da09aed1-5516-4169-9a29-8239a691f952

	column 'Name'
		dataType: string
		lineageTag: 1da7ad5b-355e-420b-bd40-694573005199
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Sales First 180 Days'
		dataType: double
		lineageTag: 7f2d2443-fa4f-4a88-8f94-f938be65c7ca
		summarizeBy: sum
		sourceColumn: Sales First 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Last 180 Days'
		dataType: double
		lineageTag: 7a2e6eb7-629c-46d6-bda2-75d8a1632fca
		summarizeBy: sum
		sourceColumn: Sales Last 180 Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Starting Size'
		dataType: string
		lineageTag: 100cc9cd-59d2-4aaf-a42c-44756e7f1cf5
		summarizeBy: none
		sourceColumn: Starting Size

		annotation SummarizationSetBy = Automatic

	column 'Ending Size'
		dataType: string
		lineageTag: 92eed4e0-4e13-43ca-bf15-2c43cf26e273
		summarizeBy: none
		sourceColumn: Ending Size

		annotation SummarizationSetBy = Automatic

	partition sales_final_dataset = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("\home\russ\Documents\coding_projects\portfolio_projects\powerbpy\examples\data\sales_final_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"Name", "Sales First 180 Days", "Sales Last 180 Days", "Starting Size", "Ending Size"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"Name", type text}, {"Sales First 180 Days", type number}, {"Sales Last 180 Days", type number}, {"Starting Size", type text}, {"Ending Size", type text}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

