table wa_bigfoot_by_county
	lineageTag: 0dda0214-ae83-47f1-8349-b18442fd2e5a

	column 'county'
		dataType: string
		lineageTag: 83965237-3fcb-423e-b407-90d5b27f4931
		summarizeBy: none
		sourceColumn: county

		annotation SummarizationSetBy = Automatic

	column 'season'
		dataType: string
		lineageTag: f29c94b4-0829-43d6-ba38-034a4ab42fb1
		summarizeBy: none
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column 'count'
		dataType: double
		lineageTag: cb8a9755-3e0f-4cc7-b60d-77a90c214fd6
		summarizeBy: sum
		sourceColumn: count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition wa_bigfoot_by_county = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("\home\russ\Documents\coding_projects\portfolio_projects\powerbpy\examples\data\wa_bigfoot_by_county.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"county", "season", "count"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"county", type text}, {"season", type text}, {"count", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	measure 'Bin 1 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			RETURN
			bin1_LB & "-" & bin1_UB
		lineageTag: 19bf3ac3-f26e-4497-bbc4-e247bde7a5ea
	measure 'Bin 2 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			RETURN
			bin2_LB & "-" & bin2_UB
		lineageTag: bcbe1971-1709-471a-a081-5cc7f5249736
	measure 'Bin 3 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_60 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, ROUND( perc_60, 2) )
			RETURN
			bin3_LB & "-" & bin3_UB
		lineageTag: 16ea9ff7-73f2-4af3-b2d3-74406ebce48d
	measure 'Bin 4 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_60 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_80 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, ROUND( perc_60, 2) )
			VAR bin4_LB = bin3_UB + 0.01
			VAR bin4_UB = IF ( perc_60 == perc_80 || perc_80 <= bin4_LB, bin4_LB + 0.01, ROUND( perc_80, 2) )
			RETURN
			bin4_LB & "-" & bin4_UB
		lineageTag: 81844484-4ab7-4902-89f0-492a273f0927
	measure 'Bin 5 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_60 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_80 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_100 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 1 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, ROUND( perc_60, 2) )
			VAR bin4_LB = bin3_UB + 0.01
			VAR bin4_UB = IF ( perc_60 == perc_80 || perc_80 <= bin4_LB, bin4_LB + 0.01, ROUND( perc_80, 2) )
			VAR bin5_LB = bin4_UB + 0.01
			VAR bin5_UB = IF ( perc_80 == perc_100 || perc_100 <= bin5_LB, bin5_LB + 0.01, ROUND( perc_100, 2) )
			RETURN
			bin5_LB & "-" & bin5_UB
		lineageTag: 73ea1898-992a-4495-b842-a7d6857b265f
	measure 'Measure Value' = CALCULATE ( SUM ( wa_bigfoot_by_county[count] ))
		lineageTag: 4b80e752-c66d-41bf-bb39-e906ceae1a33
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bin Assignment Measure' = ```

		 VAR perc_0 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_20 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_40 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_60 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_80 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_100 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 1 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR bin1_LB = perc_0
			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, perc_20)
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, perc_40 )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, perc_60 )
			VAR bin4_LB = bin3_UB + 0.01
			VAR bin4_UB = IF ( perc_60 == perc_80 || perc_80 <= bin4_LB, bin4_LB + 0.01, perc_80 )
			VAR bin5_LB = bin4_UB + 0.01
			VAR bin5_UB = IF ( perc_80 == perc_100 || perc_100 <= bin5_LB, bin5_LB + 0.01, perc_100 )
			RETURN

				SWITCH (
					TRUE (),
					ISBLANK([Measure Value]), 0,
					[Measure Value] >= ROUND(bin1_LB,2) &&
					[Measure Value] <= ROUND(bin1_UB,2), 1,
					[Measure Value] >= ROUND(bin2_LB,2) &&
					[Measure Value] <= ROUND(bin2_UB,2), 2,
					[Measure Value] >= ROUND(bin3_LB,2) &&
					[Measure Value] <= ROUND(bin3_UB,2), 3,
					[Measure Value] >= ROUND(bin4_LB,2) &&
					[Measure Value] <= ROUND(bin4_UB,2), 4,
					[Measure Value] >= ROUND(bin5_LB,2) &&
					[Measure Value] <= ROUND(bin5_UB,2), 5

				)
			```
		formatString: 0
		lineageTag: 2f4f48eb-91c6-4d1e-b994-4fc86855c6da

	measure 'Empty Bin' =

			"No Data"
		lineageTag: 78d0d811-6d4e-4454-9a6f-31a659859466

	measure '20 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: a9ad595f-2e3c-4114-9e54-c5e09cbba79d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '40 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: e9652407-aa82-4dae-94ac-6a3e95b7961f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '60 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: 535a19ee-6022-4260-95a2-040051a933b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '80 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: 45f57001-6e68-4b51-8965-db721462b9ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '100 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 1 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: 5f329dfd-09f0-4847-be79-1dbc65db824e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

